### PR TITLE
CI: NVHPC 23.1

### PR DESCRIPTION
**Pull request by ax3l**
## Summary

Update CI to Test against the latest NVHPC release, v23.1

## Additional background

See #2378

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by ax3l** [comment]
Hi @WeiqunZhang, how do we want to we handle
```
"/home/runner/work/amrex/amrex/Src/Base/Parser/amrex_parser.lex.cpp", line 1082: error: statement is unreachable [code_is_unreachable]
  	YY_BREAK
  	^

Remark: individual warnings can be suppressed with "--diag_suppress <warning-name>"
```
?

Pragmas or CI compile flag?

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Codes/amrex/blob/e6e2fbc3cd753e82bcd95d213a4adf436f94796f/Src/Base/Parser/GNUmakefile#L4

This is how we currently handle warnings in bison and flex generated code.

**Comment by ax3l** [comment]
Just realized that's only a problem in #2378

**Comment by ax3l** [comment]
Oh, there is more in particles. Attn @atmyers ?
```
/home/runner/work/amrex/amrex/Tests/Particles/ParticleArray/main.cpp
"/home/runner/work/amrex/amrex/Src/Particle/AMReX_ParticleArray.H", line 218: error: storage class is not first [storage_class_not_first]
      auto static constexpr data_layout = DataLayoutTag;
           ^

Remark: individual warnings can be suppressed with "--diag_suppress <warning-name>"

"/home/runner/work/amrex/amrex/Src/Particle/AMReX_ParticleArray.H", line 255: error: storage class is not first [storage_class_not_first]
      auto static constexpr data_layout = DataLayoutTag;
           ^
```

**Comment by WeiqunZhang** [comment]
`auto static constexpr` -> `static constexpr auto`?

**Comment by ax3l** [comment]
Agreed. I pushed an update to this PR.

**Review by atmyers — APPROVED** [review]

**Review by WeiqunZhang — APPROVED** [review]

**Pull request merged**
