### PR TITLE
GPU kernel fusing in MLPoisson

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Comment by PaulMullowney** [comment]
Funny. Forgot about this PR.

**Comment by WeiqunZhang** [comment]
For an amr-wind test with max_grid_size=32, MLPoisson::Fsmooth went down from 2.495 to 0.6041.

All the regression tests have passed.

**Comment by PaulMullowney** [comment]
> For an amr-wind test with max_grid_size=32, MLPoisson::Fsmooth went down from 2.495 to 0.6041.
> 
> All the regression tests have passed.

Not bad.

**Comment by drummerdoc** [comment]
> > For an amr-wind test with max_grid_size=32, MLPoisson::Fsmooth went down from 2.495 to 0.6041.
> > All the regression tests have passed.
> 
> Not bad.

I'd call that a win.

**Review by asalmgren — APPROVED** [review]

**Pull request merged**
