### PR TITLE
GitHub Actions: 4 vCPUs are available now on Ubuntu and Windows

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

**Comment by WeiqunZhang** [comment]
OpenMPI does not think there are 4 cores. :thinking:

**Comment by WeiqunZhang** [comment]
However, I do see 4 cpus with `ls /sys/devices/system/cpu/`.

**Comment by WeiqunZhang** [comment]
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Review by asalmgren — APPROVED** [review]

**Pull request merged**
