### PR TITLE
Makefile tweak for OLCF

### PR DESCRIPTION
**Pull request by jaharris87**
Add CUDA version to PGI compile flags on summit.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
It seems that you could extract the version number from the output of `nvcc --version` using `shell`, `tail` and `sed`.  That will make it more future proof.

**Comment by maxpkatz** [comment]
I've been trying to avoid the CUDA specifier to the PGI compiler because we already override its choice for the CUDA toolkit by pointing to the system install (rather than whatever it comes with); this helps ensure compatibility with the nvcc part of the build.

**Comment by jaharris87** [comment]
I noticed quite a bit of difference in optimization by specifying 10.1 for OpenACC, but it probably doesn't make a difference elsewhere.

**Comment by jaharris87** [comment]
Given the feedback from @maxpkatz , I'll withdraw this PR since it seems more pervasive than I had originally thought.

**Pull request closed without merging**
