### PR TITLE
Update max_work_item_sizes for SYCL 2020

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Review by jmsexton03 — APPROVED** [review]

**Comment by WeiqunZhang** [comment]
Looks like the latest public oneAPI compile does not have the change yet.  May need to add a macro for this.

**Review by jmsexton03 — COMMENTED** [review]
As commented above, the current CI failed, so I'll un-approve it for now if that's a thing

**Comment by WeiqunZhang** [comment]
Save it for future

**Comment by WeiqunZhang** [comment]
The current version used by github CI is `#define __INTEL_CLANG_COMPILER 20220200`.

**Comment by WeiqunZhang** [comment]
There are a number of things we need to update for oneAPI 2023.  I will do it in another PR.

**Pull request closed without merging**
