### PR TITLE
SENSEI: SoA Particle Support

### PR DESCRIPTION
**Pull request by ax3l**
## Summary

Add support for pure SoA layouted particle containers for SENSEI.

## Additional background

Follow-up to #2878.

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by ax3l** [comment]
cc @c-wetterer-nelson @patrickoleary @burlen for the discussion we had today

**Comment by burlen** [comment]
`amrex::ParticleDataAdaptor` will also need to be updated.

Also, since all of our particle classes are templates, and there's no instantiations inside AMReX, the CI builds don't compile them, and any bugs won't be caught there.

I think we probably need to add regression tests that create an instance and exercise it.

We've been using the tutorials and various AMReX downstream codes for testing.

**Comment by ax3l** [comment]
Thank you @atmyers 🎉 

Cc @burlen ping for review

**Comment by c-wetterer-nelson** [comment]
this looks great! +1

I do appreciate the new `template<typename ParticleType, ...` templating. Have all the science codes successfully adopted it yet?

**Comment by burlen** [comment]
I think our exposure to this change is limited to WarpX and the AMReX tutorials. @c-wetterer-nelson would you be able to try out the tutorial and see what if any changes are needed?

**Comment by atmyers** [comment]
The CI test is compiling now - @burlen @c-wetterer-nelson do you think one of you could try this out on the tutorial?

**Comment by ax3l** [comment]
> Have all the science codes successfully adopted it yet?

@c-wetterer-nelson we update step-by-step and started with the [BLAST](https://blast.lbl.gov/) codes: [WarpX](https://github.com/ECP-WarpX/WarpX/pull/3850), [ImpactX](https://github.com/ECP-WarpX/impactx/pull/348), [HiPACE++](https://github.com/Hi-PACE/hipace/pulls?q=is%3Apr+SoA+is%3Aclosed).

This PR and #3350 are still on the way for the WarpX & ImpactX transition :)

**Comment by ax3l** [comment]
This looks great, good to merge from my side! :tada: Thank you @atmyers for all the work!
(Cannot approve since I opened it :sweat_smile:)

**Review by atmyers — APPROVED** [review]

**Pull request merged**
