### PR TITLE
HDF5 I/O and Compression 

### PR DESCRIPTION
**Pull request by houjun**
## Summary
- Update particle checkpoint/restart with HDF5 I/O using new particle access methods (#2063)
- Add (prototype) ZFP compression capability to HDF5 I/O for plotfile and particle
- Add a CI task for HDF5 I/O test (plotfile and particle checkpoint/restart)

## Checklist

The proposed changes:
- [x] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

### CODE REVIEW

**Comment by atmyers** [comment]
Hi Houjun, 

This looks good to me, thank you for adding these tests! Could you fix the conflict by merging with development? Then I think this is ready to go in.

How would you feel about moving all the HDF5-related functionality to Src/Extern/HDF5? That is more in line with how things are organized for other optional-but-supported packages, like Sundials, SENSEI, etc... 

Best,
Andrew

**Comment by houjun** [comment]
Hi @atmyers 
I just fixed the conflicts, waiting on the CI tasks to finish.
It sounds good to move the HDF5 functions to Src/Extern/HDF5, shall we do it with this pull request or open a new one?

**Comment by atmyers** [comment]
Whatever is easiest for you, I'd be fine to merge this as is, and then you could issue a follow-up PR - what do you think?

**Comment by houjun** [comment]
Let's merge this as is, I'm working on the new format that separates the variables in HDF5 datasets, as we talked about previously, and we have the code relocation as part of that pull request.

**Review by atmyers — APPROVED** [review]

**Pull request merged**
