### PR TITLE
CI: Fix oneAPI Activation

### PR DESCRIPTION
**Pull request by ax3l**
now located at `/opt/intel/oneapi/setvars.sh`

### CODE REVIEW

**Comment by ax3l** [comment]
User-defined literals broken since beta08: https://github.com/intel/llvm/issues/2187

**Comment by WeiqunZhang** [comment]
For the `_rt` literal, maybe we can use `double` when `AMREX_USE_DPCPP`.

**Comment by ax3l** [comment]
Yes, but this should be a temporary fix because it's explicitly not what the C++ standard defines: https://en.cppreference.com/w/cpp/language/user_literal

```
Only the following parameter lists are allowed on literal operators : 
( const char * ) | (1) |  
( unsigned long long int ) | (2) |  
( long double ) | (3)
...
```

Will push a work-around on this PR.

**Comment by ax3l** [comment]
Dang, we cannot trick C++:
```
/home/runner/work/amrex/amrex/Src/Base/AMReX_REAL.H:91:21: error: invalid literal operator parameter type 'double', did you mean 'long double'?
    operator"" _rt( AMREX_TMP_LONGDBL x )
                    ^~~~~~~~~~~~~~~~~~~
/home/runner/work/amrex/amrex/Src/Base/AMReX_REAL.H:74:30: note: expanded from macro 'AMREX_TMP_LONGDBL'
#   define AMREX_TMP_LONGDBL double
                             ^
```

**Comment by ax3l** [comment]
Found a work-around: [`-mlong-double-64`](https://reviews.llvm.org/D6260)
Update: ha, flag gets consumed but is ignored in `dpcpp`.

**Comment by WeiqunZhang** [comment]
We might have a workaround.  For DPC++, we use `const char*` instead of `long double`.  But we will need to implement our own `atof` because the one in `cstdlib` does not work on device.
```
constexpr Real 
operator"" _rt( const char* x )
{
    return amrex::atof(x);
}
```

**Comment by WeiqunZhang** [comment]
This works very well for gcc.  https://godbolt.org/z/rWcEqY But for clang, the constexpr function is not optimization away.  https://godbolt.org/z/GYjTMP

**Comment by WeiqunZhang** [comment]
https://godbolt.org/z/qvxE1s If we force it with a constexpr variable, it works.  But that's not how we use it.

**Comment by WeiqunZhang** [comment]
This however does not compile. https://godbolt.org/z/3Ejzbn

**Comment by WeiqunZhang** [comment]
https://github.com/intel/llvm/pull/2295  `-mlong-double-64` has been fixed.

**Review by WeiqunZhang — APPROVED** [review]

**Comment by ax3l** [comment]
Submitted a Clang/LLVM bug report/RFE as discussed on Slack: https://bugs.llvm.org/show_bug.cgi?id=47213

**Pull request merged**
