### PR TITLE
Define BL_USE_MPI compilation flag when MPI and Fortran are enabled

### LINKED ISSUE #1989: Initialization fails when MPI and Fortran are enabled
When calling `amrex_init` from Fortran:

I get the following error message:

```
*** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
```

This seems like a regression that was introduced in v21.01. I'll submit a pull request with a fix.

### PR DESCRIPTION
**Pull request by zjibben**
## Summary
Resolves #1989 

## Checklist

The proposed changes:
- [X] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
I don't think this is the right fix.

**Comment by WeiqunZhang** [comment]
We should only define `BL_USE_MPI` and `AMREX_USE_MPI` when AMReX_MPI is on.

**Comment by WeiqunZhang** [comment]
Other than that, I believe this is a valid fix.

**Comment by zjibben** [comment]
Thanks. You're right, I didn't quite do the right thing here. In fact the problem only arises due to the lack of `BL_USE_MPI`. I'll modify my commit.

**Comment by zjibben** [comment]
I just overwrote my commit. This one will only define `BL_USE_MPI` if `AMReX_MPI` is on.

**Comment by WeiqunZhang** [comment]
Great! Thanks!

**Review by mic84 — APPROVED** [review]

**Pull request merged**
