### PR TITLE
Fix a memory leak in TableData::operator=

### PR DESCRIPTION
**Pull request by WeiqunZhang**
X-Ref: https://github.com/ECP-WarpX/WarpX/pull/4779

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
Thank you! I think the copy constructor might need the same logic usually, does it?

**Comment by WeiqunZhang** [comment]
You mean copy assignment? It is deleted.

**Comment by ax3l** [comment]
@WeiqunZhang I actually meant the move constructor, but I think that's not needed there after all (nothing to clear from a previous allocation).

**Comment by WeiqunZhang** [comment]
Yes for constructor there is nothing to clear and no alias to check.

**Pull request merged**
