### PR TITLE
python script added to convert ascii amrex particle files to vtp

### PR DESCRIPTION
**Pull request by hsitaram**
I have added python scripts to convert amrex particle file to vtp format, read by paraview.

Thanks,
Hari NREL

### CODE REVIEW

**Comment by zingale** [comment]
I don't think it's a good idea to store plotfiles in the git repo itself.  github doesn't like this.  Perhaps the github large file storage could be an alternative if they are needed as an example?

**Comment by hsitaram** [comment]
No problem, I can remove them. They are not very big anyway. All of them contribute to about 1 MB.

**Comment by hsitaram** [comment]
Is it ok to leave may 3 files instead of the 20 I have in there?

**Comment by WeiqunZhang** [comment]
OK.  Let's leave 3 files.  But you may have to generate a new commit that is NOT derived from this commit.  Otherwise they will still be in the repo.   Sorry for the trouble.

**Comment by WeiqunZhang** [comment]
I guess I can squash the two commits into one.

**Pull request merged**
