### PR TITLE
Forkjoin

### PR DESCRIPTION
**Pull request by cychan-lbnl**
some changes to support forkjoin

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
It does not compile when USE_MPI=FALSE.

**Comment by cychan-lbnl** [comment]
Should be fixed now.

**Comment by WeiqunZhang** [comment]
There is a problem with

```
enum class ReduceOp : MPI_Op {
        max  = MPI_MAX,
        min  = MPI_MIN,
        sum  = MPI_SUM,
        lor  = MPI_LOR,
        land = MPI_LAND
    };
```
`MPI_Op` is not necessarily an integral type.  So this does not compile with OpenMPI.

**Comment by cychan-lbnl** [comment]
Thanks!  I changed it to use an unordered_map to convert the enum to MPI_Op type.  Hopefully that fixed it.

**Pull request merged**
