### PR TITLE
Add triangle wave function to least squares test

### PR DESCRIPTION
**Pull request by drangara**
## Summary
Add a new test case - triangle wave function - to EB viscous centroid apply(). Fix some bugs in test setup.

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
What editor do you use?  We have `.editorconfigure`.

**Comment by drangara** [comment]
> What editor do you use? We have `.editorconfigure`.

Currently just using `gvim`. Is there a plugin for that? thanks

**Comment by WeiqunZhang** [comment]
https://github.com/editorconfig/editorconfig-vim#readme  Maybe this will work.

**Comment by drangara** [comment]
> https://github.com/editorconfig/editorconfig-vim#readme Maybe this will work.

thank you. yes I have installed the plugin using vundle. I see my editor is using the rules from the `.editconfigure` file now.

**Review by asalmgren — APPROVED** [review]

**Pull request merged**
