### PR TITLE
Fix a typo in Readme

### PR DESCRIPTION
**Pull request by WeiqunZhang**
The link to Gallery did not work because of the typo.

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by etpalmer63** [comment]
I should also move the images into the AMReX-Codes.github.io repo and fix the links to point to the new location. I can do it now or afterwards?

**Review by etpalmer63 — APPROVED** [review]
Thanks!

**Comment by WeiqunZhang** [comment]
> I should also move the images into the AMReX-Codes.github.io repo and fix the links to point to the new location. I can do it now or afterwards?

Up to you

**Comment by etpalmer63** [comment]
> > I should also move the images into the AMReX-Codes.github.io repo and fix the links to point to the new location. I can do it now or afterwards?
> 
> Up to you

Let's do it afterwards then. -- Thanks

**Pull request merged**
