### PR TITLE
Allow specification of number of amr levels for MLLinOp and MLNodeLinOp

### PR DESCRIPTION
**Pull request by bsrunnels**
Currently `m_num_amr_levels` is determined by the size of the `geom` object. However, sometimes fewer AMR levels might be needed, for instance, if this is used within an AmrCore where `finest_level` is lower than `num_amr_levels`.

### CODE REVIEW

**Comment by ChrisDeGrendele** [comment]
This will help fix https://github.com/AMReX-Astro/MAESTROeX/issues/203

**Comment by bsrunnels** [comment]
Updated to include the same fix for `MLCellLinOp`.

**Comment by WeiqunZhang** [comment]
I think people should use these functions in AmrMesh, which is the base of AmrCore (and Maestro I think), `Vector<Geometry> Geom (int a_coarsest_lev, int a_finest_lev)`, `Vector<BoxArray> boxArray (int a_coarsest_lev, int a_finest_lev)` and `Vector<DistributionMapping> DistributionMap (int a_coarsest_lev, int a_finest_lev)`.

Note that sometimes we need to solve multi-level problems not starting from level 0.  The PR will not solve that problem.

**Comment by bsrunnels** [comment]
Oh ok, so in this case use

     linop.define(Geom(0,finest_level), grids, DistributionMap(0,finest_level), info).

That works for me - thanks.

**Pull request closed without merging**
