### PR TITLE
blueprint: wrap amr nesting info for use in ascent

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
@mclarsen  can you double check the commits in this PR, our fork was in a strange state, I want to make sure I didn't miss anything.

**Comment by mclarsen** [comment]
@cyrush this looks like everything

**Comment by mclarsen** [comment]
@cyrush @ax3l Does the new cmake logic look sane to you?

**Comment by cyrush** [comment]
@mclarsen cmake changes look good to me

**Comment by cyrush** [comment]
@atmyers i think this batch of changes is ready, can you help us with this PR?

**Review by atmyers — APPROVED** [review]
Looks good to me.

**Comment by cyrush** [comment]
@atmyers @WeiqunZhang thanks!

**Pull request merged**
