### PR TITLE
Free MPI_Datatype defined by AMReX

### PR DESCRIPTION
**Pull request by WeiqunZhang**
## Summary
This fixes a one-time memory leak in MPI_Datatypes defined by AMReX as reported in #1525.

## Checklist

The proposed changes:
- [x] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

### CODE REVIEW

**Review by kngott — APPROVED** [review]

**Comment by pedro-ricardo** [comment]
Unfortunately I found  more errors. But now in the example compilation link.
I'm compiling AMReX with:
```
cmake -DCMAKE_INSTALL_PREFIX=/opt/apps/amrex/20.11-mpich-3.3.1-petsc-3.11.3 \
-DDIM=3 -DENABLE_EB=yes -DENABLE_PARTICLES=yes \
-DENABLE_FORTRAN=yes -DENABLE_FORTRAN_INTERFACES=yes \
-DENABLE_MPI=yes -DMPI_ROOT=/opt/apps/mpich/3.3.1-gcc-9.1.1 \
-DENABLE_HYPRE=yes -DHYPRE_ROOT=/opt/apps/petsc/3.11.3-gcc-9.1.1-mpich-3.3.1 \
-DENABLE_HDF5=yes -DHDF5_ROOT=/opt/apps/hdf5/1.10.5-gcc-9.1.1-mpich-3.3.1 \
-DENABLE_PETSC=yes -DPETSC_DIR=/opt/apps/petsc/3.11.3-gcc-9.1.1-mpich-3.3.1 \
-DBUILD_SHARED_LIBS=true -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=true ..
```

And when linking to build the executable the following errors appear. It does not happens in `v20.10`.

```
lib/libamrex.so: undefined reference to `amrex_fi_delete_flash_fluxregister'
lib/libamrex.so: undefined reference to `amrex_fi_new_flash_fluxregister'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_load_2'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_store'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_load_1_area'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_load_area_ifd'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_load_2_area'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_communicate'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_store_area_ifd'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_load_1'
lib/libamrex.so: undefined reference to `amrex_fi_flash_fluxregister_store_area'
```

**Comment by pedro-ricardo** [comment]
Sorry wrong branch ...

**Comment by pedro-ricardo** [comment]
Couldn't build the `mpi_type` branch with the options I need. So I cherry picked the last commit into version 20.10 and it works just fine now.

```
==10010== HEAP SUMMARY:
==10010==     in use at exit: 0 bytes in 0 blocks
==10010==   total heap usage: 6,709 allocs, 6,696 frees, 44,067,502 bytes allocated
==10010== 
==10010== All heap blocks were freed -- no leaks are possible
==10010== 
==10010== For lists of detected and suppressed errors, rerun with: -s
==10010== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

When compiling the `mpi_type` branch the cmake doesn't accept the flags I set.
```
Manually-specified variables were not used by the project:

    DIM
    ENABLE_EB
    ENABLE_FORTRAN
    ENABLE_FORTRAN_INTERFACES
    ENABLE_HDF5
    ENABLE_HYPRE
    ENABLE_MPI
    ENABLE_PARTICLES
    ENABLE_PETSC
    HDF5_ROOT
    HYPRE_ROOT
    PETSC_DIR
```

**Comment by WeiqunZhang** [comment]
There were some backward incompatible changes in the cmake system recently (#1490).  You need to replace `ENABLE_` with `AMReX_` for AMReX options and I think `DIM` is now `AMReX_SPACEDIM` in cmake.

**Comment by pedro-ricardo** [comment]
I see :+1: Thanks for the heads up.

This fix issue #1525

**Pull request merged**
