### PR TITLE
Add anonymous namespace back to parameters in AMReX_Amr.cpp

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Comment by maximumcats** [comment]
I've actually been relying on this change in Castro:

https://github.com/AMReX-Astro/Castro/blob/main/Source/driver/Castro.cpp#L146-L148

https://github.com/AMReX-Astro/Castro/blob/main/Source/driver/Castro.cpp#L472-L476

Is there a way I can continue to do this?

**Comment by WeiqunZhang** [comment]
We can add `compute_new_dt_on_regrid` as a static member of `Amr`.

**Comment by maximumcats** [comment]
Thank you! Can you also add a static setter function? e.g. a public
```
static void setComputeNewDtOnRegrid (int compute_new_dt) { compute_new_dt_on_regrid = compute_new_dt; }
```
I need that since read_params() is a static function too.

**Comment by WeiqunZhang** [comment]
Sure

**Review by maximumcats — APPROVED** [review]

**Pull request merged**
