### PR TITLE
`ParmParse:addFile`: User-Friendly Error

### PR DESCRIPTION
**Pull request by ax3l**
## Summary

If a file added via `ParmParse:addFile` does not exist, we did not yet receive a user-friendly error message. This fixes this in a way that does not hammer the file system from all MPI ranks.

## Additional background

Follow-up to #2842 #2936 #3440

X-ref: https://github.com/ECP-WarpX/WarpX/issues/5283 https://github.com/ECP-WarpX/impactx/pull/704

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
I thought it's going to say something like `Couldn't open file: xxxx`. Is that a python thing that the error message gets lost? Or is it you want ParmParse::addFile to be explicitly mentioned (instead of looking it up in Backtrace files)?

Anyway there is a function called `amrex::FileExists` that you can use. Also do we need bcast the information and print on all processes? If the I/O process aborts, it will abort other processes too.

**Comment by WeiqunZhang** [comment]
So it could just
```
if (ParallelDescriptor::IOProcessor()) {
    AMREX_ALWAYS_ASSERT_WITH_MESSAGE(FileExists(filename), "xxxxxx");
}
```

**Comment by ax3l** [comment]
Thanks! Yes the error message I got so far looks not as clean as it could be.

If we do the check & abort inside an `if(IOProc)` then technically another MPI process could front-run the check and maybe obfuscate the error message again at scale (or even trigger abort before the clear error messsage is thrown). The BCast is a bit safer... What do you think?

**Comment by AlexanderSinn** [comment]
To prevent other errors later, a barrier should be enough.

**Comment by WeiqunZhang** [comment]
There is already a barrier after this in reading and bcast the file, which also produce `Couldn't open file: xxxx` if I/O fails.

**Comment by WeiqunZhang** [comment]
My point is the fewer lines of code, the better, unless the code is hard to read.

**Review by WeiqunZhang — APPROVED** [review]

**Pull request merged**
