### PR TITLE
store the CUDA version in build info

### PR DESCRIPTION
**Pull request by zingale**
## Summary

For codes that use makebuildinfo_C.py, , this now allows you to get the CUDA version to potentially store in output files

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
For whatever reason, the CI jobs did not start.  Could you merge development into this branch to re-trigger the CI?

**Comment by zingale** [comment]
merged development

**Comment by WeiqunZhang** [comment]
I think we had better include `AMReX_Config.H`, which has `AMREX_USE_CUDA` defined.

**Comment by zingale** [comment]
added

**Review by WeiqunZhang — APPROVED** [review]

**Pull request merged**
