### PR TITLE
Fortran build routine for non-owning fab

### PR DESCRIPTION
**Pull request by kweide**
@WeiqunZhang Your improvement to #308 works for me, thanks!

I wanted something like this on the Fortran side, too, i.e., a routine 
"that takes a pointer and builds a non-owning" FAB. Thus this new PR.

Again please let me know if you would prefer to do this in a different way - or just make appropriate changes.

### CODE REVIEW

**Comment by kweide** [comment]
(1) It's fine to have the generic name be the same as one of the specific names in Fortran, at least I am not aware of any problems with it. But to avoid confusion, sure we can change one of the names.

(2) Yes I did not pay much attention to error checking. My idea of the interface was that bx has to be consistent with the Fortran pointer passed in, that is the sizes in all three spatial indices have to be the same, and nc `.le.` the last size of dp.

**Comment by kweide** [comment]
(Is there an ASSERT macro for use in Fortran code?)

**Comment by WeiqunZhang** [comment]
Unfortunately, the word macro does not appear in the Fortran standard and it's known some compilers don't like it.   But `ifdef` seems to have wide support and we have relied on it anyway.  So you can put the checks inside `#ifdef AMREX_DEBUG`.

**Comment by kweide** [comment]
I have pushed an additional commit to address your points (1) and (2).

I am using ERROR STOP, do not know about compatibility but I assume that Fortran compilers that are modern enough to compile AMReX understand it. My old GNU Fortran (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 does. Is there another preferred way - for AMReX Fortran code in particular?

**Comment by WeiqunZhang** [comment]
We like to use `amrex_error` in `amrex_error_module`.   For example, `call amrex_error("error message")`.   This could provide a backtrace.

**Comment by kweide** [comment]
Now using `amrex_error` as suggested.

**Pull request merged**
