### PR TITLE
Add headings and steps to plot vector field in ParaView doc section

### PR DESCRIPTION
**Pull request by etpalmer63**
## Summary
Adds directions for ploting a vector field from 3 separate scalar values using the Calculator filter.
Also split up the ParaView section by adding some headings.

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [x] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
Could we make the png file smaller?  When we make a compressed tar ball of amrex, about 70% of the size is used by png files in Docs/.

**Comment by etpalmer63** [comment]
It should be down to about 136K now.

**Comment by etpalmer63** [comment]
I think I could also similarly reduce some of the other images without a lot of degredation using indexed colors. Let me know if you want me to give it a try.

**Comment by WeiqunZhang** [comment]
The problem of that is although it reduces the tar ball size, it will increase the git repo size because both versions will exist in git.

**Review by WeiqunZhang — APPROVED** [review]

**Pull request merged**
