### PR TITLE
Fix index to make it work in all dimensions.

### PR DESCRIPTION
**Pull request by maikel**
This fixes an issue I had when I tried using EB in 2 dimensions.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
This is not a bug.  `Vector<int> a_ngrow` happens to have size of 3, but it is not for three dimensions.  The three integers are for `EBSupport::basic`, `volume` and `full`, respectively.

**Comment by maikel** [comment]
Ok. I changed that because I got an out of bounds error in my code (where I use the full support). I will reinvestigate.

**Comment by WeiqunZhang** [comment]
In that case, you need to pass a Vector of size 3.  For example, https://github.com/AMReX-Codes/amrex/blob/master/Src/Amr/AMReX_AmrLevel.cpp#L116

**Comment by maikel** [comment]
I understand.. it worked. Thank you!

**Pull request closed without merging**
