### PR TITLE
Revert "Disable SYCL on Nvidia and AMD CIs (#3726)"

### PR DESCRIPTION
**Pull request by WeiqunZhang**
This reverts commit 33dea1f728817941740ca569cff0bfb268d3849f. The APT issue has been fixed.

X-ref #3726

### CODE REVIEW

**Comment by ax3l** [comment]
cc @nmnobre just FYI

**Comment by WeiqunZhang** [comment]
On my fork I got this. So we may need to wait for a couple of days.
```
Err:11 https://developer.codeplay.com/apt all/main amd64 Packages
  File has unexpected size (602 != 598). Mirror sync in progress? File has unexpected size (602 != 598). Mirror sync in progress? [IP: 139.162.232.154 443]
  Hashes of expected file:
   - Filesize:598 [weak]
   - SHA256:6b68d6133d24396c2d909828199d0b69233e23a4e563ac38cfbc4d5923dbec6c
   - SHA1:23994604c9d8eb42711eb0f1c874163a49fa3a8d [weak]
   - MD5Sum:0bb9fc998633a460789746a33cde2643 [weak]
  Release file created at: Wed, 31 Jan 2024 12:39:18 +0000
  ```

**Comment by WeiqunZhang** [comment]
@ax3l This works now. Still have to do a `apt-get clean` before `apt-get update`.

**Review by ax3l — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
