### PR TITLE
MLMG::apply: need to apply inhomogeneous Neumann BC

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Comment by drummerdoc** [comment]
BTW, why it inhomogeneousNeumann and not InhomogeneousNeumann? (this is actually a new keyword to me!)

**Comment by WeiqunZhang** [comment]
Are you referring to "i" vs. "I" or the missing "e"?  There is a typo in the commit message.

**Comment by drummerdoc** [comment]
"i" versus "I" in the keyword. I know...trivial.

**Comment by drummerdoc** [comment]
No, what I meant was the LinOp::InhomogeneousNeumann keyword, not the title of the PR!  though now I can't find the commit in this where that was added....

**Comment by WeiqunZhang** [comment]
I understand that, it's just why not fix the typo in commit message. But I still don't understand what you mean.

```
    enum struct LinOpBCType : int {                                                                                                                                                                        
        interior         = 0,                                                                                                                                                                              
        Dirichlet        = AMREX_LO_DIRICHLET,                                                                                                                                                             
        Neumann          = AMREX_LO_NEUMANN,                                                                                                                                                               
        reflect_odd      = AMREX_LO_REFLECT_ODD,                                                                                                                                                           
        Marshak          = AMREX_LO_MARSHAK,                                                                                                                                                               
        SanchezPomraning = AMREX_LO_SANCHEZ_POMRANING,                                                                                                                                                     
        inflow           = AMREX_LO_INFLOW,                                                                                                                                                                
        inhomogNeumann   = AMREX_LO_INHOMOG_NEUMANN,                                                                                                                                                       
        Periodic         = AMREX_LO_PERIODIC,                                                                                                                                                              
        bogus            = AMREX_LO_BOGUS                                                                                                                                                                  
    };   ```

What's the change you want? `inhomogNeumann` -> `InhomogNeumann`?  There is neither `InhomogeneousNeumann` or `inhomogeneousNeumann` in the repo.

**Comment by WeiqunZhang** [comment]
`LinOpBCType::inhomogNeumann` was introduced in this commit f599e85af1e33ac7c9731.

**Comment by drummerdoc** [comment]
I typed instead of copy paste, my bad.  It was an OCD comment about consistency.  You'll admit that the enums are not consistent in case, and I'll admit that it doesn't matter much.  It prevents being able to guess while coding, but maybe guessing is bad.

**Pull request merged**
