### PR TITLE
Add GPU support to AMReX

### PR DESCRIPTION
**Pull request by maxpkatz**
This PR adds GPU support to AMReX using CUDA. Core FAB functionality works on GPUs and data is allocated using CUDA managed memory or device memory.

### CODE REVIEW

**Comment by maxpkatz** [comment]
There are a few places where I still want to insert ifdef's but in general I think this is now ready to be reviewed. @zingale can you please run the Castro test suite on this branch.

**Comment by xinshengqin** [comment]
There were 3 reviewers suggested by github originally. I accidentally click on one of them, which removed other people from the list.
Now I just added the two people who I think were on the list back.

**Comment by zingale** [comment]
here's the test suite run using this branch:
http://bender.astro.sunysb.edu/Castro/test-suite/test-suite-amrex-pgi/2017-08-07-003/index.html

**Comment by maxpkatz** [comment]
Closing until this is ready.

**Pull request closed without merging**
