### PR TITLE
amrex::Vector implicit conversion from std::vector

### PR DESCRIPTION
**Pull request by maikel**
Hi,

this change allows to pass `std::vector<T, Allocator>` objects directly to functions which take an  `amrex::Vector<T, Allocator>` argument. Currently one need to call another constructor as in `amrex::Vector<T>(v.begin(), v.end())`

What do you think?

### CODE REVIEW

**Comment by maxpkatz** [comment]
I noticed a need last month for something which takes only an `amrex::Vector<T>` as an argument (e.g. `CoordSys::GetCellLoc`) but that I wanted to fill with an `amrex::Vector<T, allocator>` (i.e. a `DeviceVector`). Is that what this would allow? It wasn't clear to me from the description.

**Comment by maikel** [comment]
No this is merely a conversion from the standard vector `std::vector<T, Allocator>` to `amrex::Vector<T, Allocator>`. I think you ask for a copy when the Allocator type changes. But this depends very heavily on the allocators in question. In this case I think you do not come around the copy constructor `amrex::Vector<T, Allocator2>(v.begin(), v.end())`, because even the notion of memory and pointers could be completely different.

**Comment by WeiqunZhang** [comment]
It's probably not good that the deep copy is hidden from the user.  Maybe make it explicit?

**Comment by WeiqunZhang** [comment]
`Vector() = default;` Is that necessary given that there is already `using std::vector<T, Allocator>::vector;`?

**Comment by WeiqunZhang** [comment]
Interesting.  Seems that once there is a user provided ctor, the default one is no longer generated even with `using std::vector::vector` and `std::vector` has a default ctor.

**Comment by WeiqunZhang** [comment]
I guess the explanation is the user deleted default ctor blocks the default ctor of base class because they have the same signature.

**Comment by WeiqunZhang** [comment]
If we make it explicit, you have to type more and it's not clear it's better than simply passing `{v.begin(),v.end()}` without any changes.

**Comment by maikel** [comment]
The hidden copy is a valid point. But instead of an explicit constructor I prefer no change at all.

**Comment by maikel** [comment]
Btw, I think the need for the default constructor is a compiler issue and not mandated by the standard.

**Pull request closed without merging**
