### PR TITLE
Replace sprintf with snprintf to fix compiler warnings

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
Splendid! Does this need the include `<stdio>` for robustness?
https://en.cppreference.com/w/cpp/io/c/fprintf

**Comment by WeiqunZhang** [comment]
Since these are cpp files, I am not worried about it.  (`cstdio` has been indirectly included by including AMReX.H).

**Comment by WeiqunZhang** [comment]
Anyway, it does not hurt to add cstdio.

**Review by ax3l — APPROVED** [review]
Perfect, thx.

**Pull request merged**
