### PR TITLE
make clang-tidy recognize .H as a header

### PR DESCRIPTION
**Pull request by zingale**
## Summary

the output of  `clang-tidy --dump-config`  shows that .H is not recognized as a header

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by zingale** [comment]
hmmm... the version of `clang-tidy` in the CI doesn't seem to like this.  But it does fix things when I run locally with clang-tidy 17

**Comment by zingale** [comment]
indeed, this option was only added in clang-tidy 17:
https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/ReleaseNotes.html

there must be another way to tell clang-tidy to recognize the headers for old versions.  At the moment, clang-tidy is not doing all the checks cause it doesn't treat .H as a header

**Comment by WeiqunZhang** [comment]
We can add this to the config file for now.
```
CheckOptions:
    - key:             bugprone-dynamic-static-initializers.HeaderFileExtensions
      value:           ';H;h;hh;hpp;hxx'
    - key:             bugprone-suspicious-include.HeaderFileExtensions
      value:           ';H;h;hh;hpp;hxx'
    - key:             google-global-names-in-headers.HeaderFileExtensions
      value:           ';H;h;hh;hpp;hxx'
    - key:             google-build-namespaces.HeaderFileExtensions
      value:           ';H;h;hh;hpp;hxx'
    - key:             misc-definitions-in-headers.HeaderFileExtensions
      value:           ';H;h;hh;hpp;hxx'
    - key:             misc-use-anonymous-namespace.HeaderFileExtensions
      value:           ';H;h;hh;hpp;hxx'
```

**Comment by WeiqunZhang** [comment]
I tested the `CheckOptions` above on my local branch. it does seem to work. I now see
/home/runner/work/amrex/amrex/Src/Particle/AMReX_Particle.H:16:1: error: do not use unnamed namespaces in header files [google-build-namespaces,-warnings-as-errors]
namespace
^

**Comment by zingale** [comment]
okay.  I'll update the PR

**Comment by WeiqunZhang** [comment]
There will be many errors to fix. Do you want me to help?

**Comment by zingale** [comment]
I can help.  But I'm working through Castro and Microphysics first.  Maybe we hold this for a little bit until the other tidy PRs are all done.

**Comment by ax3l** [comment]
fyi @lucafedeli88

**Comment by WeiqunZhang** [comment]
After #3867, we can go back to the first commit of this PR.

**Review by WeiqunZhang — APPROVED** [review]

**Pull request merged**
