### PR TITLE
Add OpenMP to EMPIC; add OpenACC and OpenMP to HeatEquation_EX1_C and reorganize

### PR DESCRIPTION
**Pull request by ylunalin**
Also added a line in the make system to add .OMPOL suffix to executables if USE_OMP_OFFLOAD flag is used.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
I changed the merge base from master branch to development.  Could you fix the conflicts?  Note that there have been changes to the two tutorials.   Please make sure `Tutorial/Particles/ElectromagneticPIC/CUDA` and CUDA version of `Tutorials/GPU/HeatEquation_EX1_C` still work.

**Comment by ylunalin** [comment]
I checked the CUDA versions of the two tutorials and the new additions, all can compile and run.

**Comment by atmyers** [comment]
This commit: 

https://github.com/AMReX-Codes/amrex/pull/398/commits/8046c86311d1f7a69e34e83d180fc9e93440717f

ended up manually touching a lot of files. I'm concerned that this will make the git history confusing, since those changes were actually already in the repo. Do you think you could start from a fresh copy of the `development` branch, and then add in the commits for your new tutorials on top of that? We can talk on Slack about the process if you want.

**Comment by ylunalin** [comment]
Starting from fresh copy sounds good. I’ll ping you on Slack, at a dentist appt right now, will be back in about an hour! 

L

On Jan 24, 2019, at 3:21 PM, Andrew Myers <notifications@github.com> wrote:

This commit:

8046c86

ended up manually touching a lot of files. I'm concerned that this will make the git history confusing, since those changes were actually already in the repo. Do you think you could start from a fresh copy of the development branch, and then add in the commits for your new tutorials on top of that? We can talk on Slack about the process if you want.

**Comment by atmyers** [comment]
This has been superseded by #401.

**Pull request closed without merging**
