### PR TITLE
Add CodeQL Scanning

### PR DESCRIPTION
**Pull request by ax3l**
## Summary

[**GitHub code scanning**](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning): [evolved from LGTM.com](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).

[`codeql.yml` workflow file for GitHub Actions](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually) 

## Additional background

- https://github.com/ECP-WarpX/WarpX/pull/3555
- https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#editing-a-code-scanning-workflow

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
Could we add a concurrency block to turn on cancel-in-progress?

**Comment by ax3l** [comment]
Great point, added.

**Comment by WeiqunZhang** [comment]
If we add this check, we need to address all the issues raised by it so that it shows a green check.  It might be hard to fix all the python scripts.  Some py scripts are outdated and can probably be removed.  But maybe we can disable the check on python for now and focus on fixing C++ issues first.  (Although I cannot find the exact breakdown, it seems that most of the issues are from the python code.).

**Comment by WeiqunZhang** [comment]
And I am happy to help fixing all the C++ issues raised.

**Comment by ax3l** [comment]
> If we add this check, we need to address all the issues raised by it so that it shows a green check.

The way this works is that the check is only non-green if a PR introduces new issues. So we can merge it already and then other PRs stay green.

>  But maybe we can disable the check on python for now and focus on fixing C++ issues first.

I agree, the Python side adds too much noise for now. Will comment out.

**Comment by zingale** [comment]
I can start taking a look at the python in there -- a lot of it is probably mine, and some might not be needed any more, others need updates.

**Comment by WeiqunZhang** [comment]
> I can start taking a look at the python in there -- a lot of it is probably mine, and some might not be needed any more, others need updates.

Yes.  For example, helmeos.py can be deleted or moved to the Microphysics repo.

**Comment by ax3l** [comment]
So, shall we merge? :)

**Review by WeiqunZhang — APPROVED** [review]

**Pull request merged**
