### PR TITLE
Add support for SZ compression in HDF5 output

### PR DESCRIPTION
**Pull request by houjun**
## Summary
Add support for SZ compression in HDF5 output, works for plot file and particle checkpoint (floating point data only).
See Tests/HDF5Benchmark/inputs for example usage.

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [x] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by atmyers** [comment]
Hi Houjun,

Thank you for adding this feature! Do you think you could add some information to our IO documentation [here](https://amrex-codes.github.io/amrex/docs_html/IO_Chapter.html). and possible to the visualization section [here](https://amrex-codes.github.io/amrex/docs_html/Visualization_Chapter.html)? 

It would not need to be long, just a short description of what features are available, how to use them, how to visualize the output, etc...

**Comment by houjun** [comment]
OK, I'll write something down and include in this pull request

**Comment by houjun** [comment]
@atmyers Just added some description for the HDF5 output, please take a look and let me know if anything needs to be changed.

**Review by atmyers — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
