### PR TITLE
Fix typos in FaceDivFree interior interpolation.

### PR DESCRIPTION
**Pull request by cgilet**
The problem was masked in test in amrex/Tests/DivFreePatch because all three components were the same.

## Checklist

The proposed changes:
- [ x] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [x] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by BenWibking** [comment]
This will affect us once we turn on AMR for our MHD problems. Could the test also be updated to catch the bug?

**Comment by kngott** [comment]
I don't have the math in front of me, so I can't fully confirm this is correct, but the change _looks_ correct, based on the pattern, so I trust it. 😄

**Review by kngott — APPROVED** [review]

**Comment by cgilet** [comment]
@BenWibking , yes, I'm looking at updating the test too. That's part of why this is still a draft. 

Do you also use the fortran interface for divergence-preserving interpolation? I haven't looked at that, or anything specific to E&M, since my use cases don't have that.

**Comment by BenWibking** [comment]
> @BenWibking , yes, I'm looking at updating the test too. That's part of why this is still a draft.
> 
> Do you also use the fortran interface for divergence-preserving interpolation? I haven't looked at that, or anything specific to E&M, since my use cases don't have that.

No, only the C++ interface.

**Pull request merged**
