### PR TITLE
CI: Fix HIP GPG Key

### PR DESCRIPTION
**Pull request by ax3l**
## Summary

Split downloading and adding.
```
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
```

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by ax3l** [comment]
Looks more like temporary DNS issues from Azure / GitHub actions to repo.radeon.com...
```
curl: (6) Could not resolve host: [repo.radeon.com](http://repo.radeon.com/)
```

**Comment by ax3l** [comment]
This PR will nonetheless fix the warning:
```
Warning: apt-key output should not be parsed (stdout is not a terminal)
```
once the DNS issue is resolved.

**Review by WeiqunZhang — APPROVED** [review]

**Comment by etpalmer63** [comment]
I still see the warning in the hip CI runs.  

```
Run .github/workflows/dependencies/dependencies_hip.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  311[6](https://github.com/AMReX-Codes/amrex/runs/6614016223?check_suite_focus=true#step:3:7)  100  3116    0     0  1[9](https://github.com/AMReX-Codes/amrex/runs/6614016223?check_suite_focus=true#step:3:10)354      0 --:--:-- --:--:-- --:--:-- 19354
Warning: apt-key output should not be parsed (stdout is not a terminal)
```
Sadly, I have no helpful suggestions. :disappointed: 

Also, this same issue came up in the other repos using wget for their hip CI. Seems to be resolved now.

**Comment by ax3l** [comment]
This might work:
https://stackoverflow.com/a/49462622/2719194
```bash
export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
```

**Pull request merged**
