### PR TITLE
Workaround for Windows omp_lock_t issue

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
Sorry there was a typo.

**Comment by ax3l** [comment]
Currently testing this in the 24.05 release roll-outs on conda-forge.

**Comment by ax3l** [comment]
@WeiqunZhang your work-around does the trick! :tada: 
https://github.com/conda-forge/warpx-feedstock/pull/83

**Comment by WeiqunZhang** [comment]
I tested the code for Windows on Linux by changing `#if defined(_WIN32)` to `#if !defined(_WIN32)` and ran some tests. It worked.

**Review by ax3l — APPROVED** [review]
Thanks!

Ok, then let us use this type erasure work-around for now. I am still positive this is a conda-forge tools issue, because we cannot see it in CI here, but this is a good work-around :)

**Pull request merged**
