### PR TITLE
Add link to 'small cell problem' section that got moved to

### PR DESCRIPTION
**Pull request by cgilet**
AMReX-Hydro's documentation. Also add more details on EB data.

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [x] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by cgilet** [comment]
@etpalmer63 This still needs some work, as I don't think I got the organization quite right. We definitely need to link to the 'small cell problem' section in AMReX-Hydro, but I don't quite have the intersphinx mapping working just yet. If you see my error, please help.

**Comment by etpalmer63** [comment]
I got it to work with a hard coded tag. Now I'm updating AMReX-Hydro to also use the auto-generated section labels (same as IAMR). Then I will try to work out the exact syntax.

**Comment by etpalmer63** [comment]
I saw you added a tag for redistribution. So I just linked to that instead of waiting for the Hydro doc changes to go through.

**Review by etpalmer63 — COMMENTED** [review]
Looks good! Thanks for your work!

**Comment by cgilet** [comment]
Thanks for the help @etpalmer63

**Review by etpalmer63 — APPROVED** [review]

**Pull request merged**
