### PR TITLE
Adding ILU smoothing parameters for Hypre interface.

### PR DESCRIPTION
**Pull request by PaulMullowney**
## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [x] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
@PaulMullowney Is there any minimum hypre version requirement for these smoothers?

**Comment by PaulMullowney** [comment]
> @PaulMullowney Is there any minimum hypre version requirement for these smoothers?

These new ILU solvers were originally introduced in version 2.19, with the GPU support coming in version 2.21

**Review by WeiqunZhang — APPROVED** [review]

**Comment by WeiqunZhang** [comment]
Unfortunately, it does not compile with hypre 2.19 or 2.20.

**Comment by PaulMullowney** [comment]
Ok. I'll investigate. It compiles off Hypre master which is past version 2.22.

**Comment by WeiqunZhang** [comment]
Thanks!  We could bump up the hypre version requirement in the cmake build system, once we know the minimum.

**Comment by PaulMullowney** [comment]
I was able to get AMReX GPU/Cuda to build with Hypre 2.21, 2.22, 2.22.1, and 2.23. I think we can set the minimum version to 2.21.

**Comment by WeiqunZhang** [comment]
Thanks for the information!

**Pull request merged**
